-- =============================================================================
-- LRI Automated Commentary Demo -- Cleanup
-- =============================================================================
-- Drops all demo objects to avoid recurring warehouse and storage costs.
-- Run this when you are done with the demo and no longer need the data.
--
-- Usage:  snow sql -c DEMO -f snowflake/cleanup.sql
-- =============================================================================

USE SCHEMA LRI_DEMO.LRI_BASE;

-- Views (09, 07, 06)
DROP VIEW IF EXISTS V_APPROACH_SUMMARY;
DROP VIEW IF EXISTS V_COMMENTARY_COMPARISON;
DROP VIEW IF EXISTS V_COMMENTARY_SCORED;
DROP VIEW IF EXISTS V_COB_SUMMARY;
DROP VIEW IF EXISTS V_REPORT_GRID;
DROP VIEW IF EXISTS V_PROMPT_ALL;
DROP VIEW IF EXISTS V_METRIC_FACTS;

-- Procedures (10, 08)
DROP PROCEDURE IF EXISTS SP_GENERATE_STARTER(DATE, VARCHAR);
DROP PROCEDURE IF EXISTS SP_GENERATE_COMMENTARY(DATE, VARCHAR, VARCHAR, BOOLEAN, VARCHAR);

-- Functions (10, 03)
DROP FUNCTION IF EXISTS FN_STARTER_PROMPT(OBJECT, ARRAY, VARCHAR, OBJECT);
DROP FUNCTION IF EXISTS FN_STARTER_PROMPT(OBJECT, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS FN_FMT(FLOAT, INT);
DROP FUNCTION IF EXISTS FN_FMT_PRETTY(FLOAT, INT);
DROP FUNCTION IF EXISTS FN_URAND(INT, INT);
DROP FUNCTION IF EXISTS FN_BREACH_AMOUNT(FLOAT, FLOAT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS FN_UTILIZATION(FLOAT, FLOAT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS FN_BREACH_LEVEL(FLOAT, FLOAT, FLOAT, FLOAT, VARCHAR, FLOAT);

-- Tables (08, 04, 02)
DROP TABLE IF EXISTS AI_COMMENTARY;
DROP TABLE IF EXISTS DIM_METRIC_DEFINITION;
DROP TABLE IF EXISTS LIMITS_INDICATORS_REPORT_DATA;

-- Infrastructure (01)
DROP WAREHOUSE IF EXISTS LRI_DEMO_WH;
DROP SCHEMA IF EXISTS LRI_DEMO.LRI_BASE;
DROP DATABASE IF EXISTS LRI_DEMO;
